import { SUPPORTED_WALLETS, useWallets } from '@romeblockchain/wallet'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  const { handleConnect, selectedWallet, setSelectedWallet } = useWallets()
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        {Object.keys(SUPPORTED_WALLETS).map((key, index) => {
          const wallet = SUPPORTED_WALLETS[key]
          const isActive = selectedWallet === wallet.wallet

          return (
            <button
              style={{
                background: isActive ? 'green' : 'gray',
              }}
              key={index}
              onClick={async () => {
                try {
                  await handleConnect(wallet.connector, setSelectedWallet, wallet.wallet, null, 1)
                } catch (error) {
                  console.log(error)
                }
              }}
            >
              {wallet.wallet}
            </button>
          )
        })}
      </div>
    </div>
  )
}
