export default {
  SEARCH_INPUT_LENGTH_MINIMUM: process.env.REACT_APP_SEARCH_INPUT_LENGTH_MINIMUM ?? 2,
  SEARCH_ASYNC_DELAY: process.env.REACT_APP_SEARCH_ASYNC_DELAY ?? 300,
  SEARCH_ASYNC_DATASET_LENGTH_MAXIMUM: process.env.REACT_APP_SEARCH_ASYNC_DATASET_LENGTH_MAXIMUM ?? 500,
  IS_ENV_PRODUCTION: process.env.REACT_APP_ROME_ENV === 'production' ? true: false,
  LOAD_LIMIT: process.env.REACT_APP_LOAD_LIMIT ?? 10
}
